# -----------------------------------------------------
# Window rules
# -----------------------------------------------------


# windowrule = float, ^(blueman-manager)$
# windowrule = float, ^(nm-connection-editor)$
# windowrule = float, ^(qalculate-gtk)$

# For matching specific applications by their window class:
windowrule = float, class:(^(blueman-manager)$)
windowrule = float, class:(^(nm-connection-editor)$)
windowrule = float, class:(^(qalculate-gtk)$)

# Browser Picture in Picture:
windowrule = float, title:(^(Picture-in-Picture)$)
windowrule = pin,   title:(^(Picture-in-Picture)$)
windowrule = move 69.5% 4%, title:(^(Picture-in-Picture)$)

windowrulev2 = opacity 0.8 active_opacity,class:^(kitty)$
windowrulev2 = opacity 0.9, class:^(code)$
windowrulev2 = opacity 0.9, class:^(obsidian)$
windowrulev2 = opacity 0.9, class:^(vivaldi-stable)$
windowrulev2 = opacity 0.9, class:^(vivaldi.*)$
windowrulev2 = noborder, class:^(ZenBrowserNative)$
windowrulev2 = float, class:^(ZenBrowserNative)$
windowrulev2 = opacity 0.6, class:^(ZenBrowser)$
windowrulev2 = opacity 0.6, class:^(zen-browser)$
